[package]
name = "elf-sframe"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = []

[dependencies]
bitflags = "2.4.2"
c-enum = "0.2.3"
tinyvec = "1.6.0"
zerocopy = { version = "0.7.32", features = ["derive", "byteorder"] }

[dev-dependencies]
anyhow = "1.0.81"
